package musicboxd.android.ui.navigation

enum class NavigationRoutes {
    HOME, SEARCH, SETTINGS, ALBUM_DETAILS, CHARTS_SCREEN, ARTIST_DETAILS, VIDEO_CANVAS,
    ADD, CUES, PROFILE, EDIT_PROFILE, CREATE_A_NEW_LIST, CREATE_A_NEW_REVIEW, REORDER_MUSIC_CONTENT_SCREEN,
    SIGN_IN, START_UP
}